- SemiconductorTestLibrary.TestStandSteps/tests/Integration/ContinuityTestTests.cs
Specify DCPower measurement sense to local sense instead of using the default remote sense.
Use remote sense fails the test on a test environment where the sensing line is floating.
Rely on ATS.
> Use local sense when initializing DCPower for the TestStandSteps integration test

- SemiconductorTestLibrary.Extensions/source/SemiconductorTestLibrary.Extensions.csproj
- SemiconductorTestLibrary.TestStandSteps/source/SemiconductorTestLibrary.TestStandSteps.csproj
Updates the TestStandSteps and Extensions csproject files to exclude net48 path from being included as a folder within the project, known to cause build issues in certain situations.
This will reduce chances of erroneous build conflicts for contributors.
None.
> Update CSProjects to Exclude net48 Path From Being Added To Project

- SemiconductorTestLibrary.Extensions/source/InstrumentAbstraction/DCPower/Source.cs
- SemiconductorTestLibrary.Extensions/source/InstrumentAbstraction/Digital/PPMU.cs
- SemiconductorTestLibrary.Extensions/tests/Unit/InstrumentAbstraction/DCPower/SourceTests.cs
- SemiconductorTestLibrary.Extensions/tests/Unit/InstrumentAbstraction/Digital/PPMUTests.cs
1. Enable `internal` DCPower methods with per-pin inputs and uncomment related tests.
2. Add PPMU ForceVoltage with per-pin voltage levels.
3. Add auto tests for methods added by #115 
To ensure better test coverage.
New tests pass locally.
> Add auto tests for DCPower/PPMU additional forcing methods

- Examples/source/DataAbstraction/PinSiteDataExamples.cs
- Examples/source/InstrumentAbstraction/ForceVoltagePPMU.cs
- Examples/source/InstrumentAbstraction/ForceVoltageSMU.cs
This PR fixes the naming of 3 PinSiteData examples that were incorrectly names SiteData:
- SiteDataBitwiseOperations --> **Pin**SiteDataBitwiseOperations
- SiteDataConvertIntToDouble --> **Pin**SiteDataConvertIntToDouble 
- SiteDataTransformUintArrayToHexString --> **Pin**SiteDataTransformUintArrayToHexString
It also corrects the indexing of `perSiteVoltageLevelsArray` in the `DifferentValuesPerSiteAcrossAllSmuPins` and `DifferentValuesPerSiteAcrossAllPpmuPins` methods.
These examples are misleading and incorrect otherwise.
Manual testing done on dev machine.
> Minor Fix To Examples

- SemiconductorTestLibrary.Extensions/source/InstrumentAbstraction/DCPower/Source.cs
Fix and Improve Documentation for the following DCPower Extension Methods:
- ConfigureOutputConnected
- ConfigureOutputEnabled
- PowerDown
The current documentation is not detailed enough. These methods have some nuance to them which needs requires elaboration. 
Just documentation changes, to a single file.
> Fix and Improve Documentation for DCPower Extension Methods

- CHANGELOG.md
- SemiconductorTestLibrary.TestStandSteps/source/ForceCurrentMeasureVoltage.cs
- SemiconductorTestLibrary.TestStandSteps/source/ForceDcCurrent.cs
- SemiconductorTestLibrary.TestStandSteps/tests/Integration/ForceCurrentMeasureVoltageTests.cs
- SemiconductorTestLibrary.TestStandSteps/tests/Integration/ForceDcCurrentTests.cs
- SemiconductorTestLibrary.TestStandSteps/tests/Integration/LeakageTestTests.cs
- SemiconductorTestLibrary.TestStandSteps/tests/Tests.SemiconductorTestLibrary.TestStandSteps.csproj
Set voltage limit low to the negative value of voltage limit high. Do coercion when the negative value is out of NI Digital instrument's valid range.
To addess this issue: https://github.com/ni/semi-test-library-dotnet/issues/136
The new auto tests pass on local dev machines.
> Correct setting of voltage limits when forcing PPMU current

- CHANGELOG.md
Organizes the Changed section of CHANGELOG.md to align with Added section for the 24.5.1 release.
Fixes typo: Mulipoint to Multipoint
Adds change to CHANGELOG.md regarding FilterPinsOrPinGroups private method being replaced in ContinuityTest method
The Change section of the 24.5.1 release was not well organized previously, and this made it hard to follow. This change also aligns it with the content organization found in the with [releases page for the 24.5.1 release](https://github.com/ni/semi-test-library-dotnet/releases/tag/v24.5.1).
Simple documentation update, no testing done or required.
> Update CHANGELOG.md to Align with 24.5.1 Release

- SemiconductorTestLibrary.TestStandSteps/source/CleanupInstrumentation.cs
- SemiconductorTestLibrary.TestStandSteps/source/DutPowerUp.cs
- SemiconductorTestLibrary.TestStandSteps/source/Shared.cs
Create a Shared.cs file and move shared definitions (currently `NIInstrumentType `and `VerifySizeOfArrayInputs`) there.
To address [this kind of usability issue](https://github.com/ni/semi-test-library-dotnet/issues/144) in a generic way.
Project build passes.
> Create a seperate file to hold shared definitions

- CHANGELOG.md
Adds a change to the CHANGELOG.md file to account for the following:
`Publish.PublishResults` extension methods now correctly publish data when there is no specific site number (i.e. -1) associated with the data, such as with SystemPins.
This should be included as a known change in the CHANGELOG.md as it addresses #155.
This is just a documentation change. No testing done or required.
> Add Change to CHANGELOG.md: Publishing Now Supports Site Agnostic Data (SystemPins)

- docs/UserGuide/toc.yml
Corrects the href path in the documentation table of contents (introduced in #161)
Docfx cannot build with the incorrect href path.
Manually ran docfx build to confirm the href path is working (this step was mistakenly overlooked when submitting #161).
> Fix href Path in Documentation Table of Contents

- .github/workflows/pr-intake.yml
The pr-intake action fails because display_title as a string cannot compare to run_number as a number.
A variable for run_number was added as a string to use in the steps below.
NA
> [Minor] Fix to typecast run_number to string for contamination check

- Examples/source/InstrumentAbstraction/MeasureVoltageMixed.cs
- docs/UserGuide/advanced/ConcurrentCodeExecution.md
Fixes the example code in the ConcurrentCodeExecution.md user guide topic and similarly the implementation in the actual MeasureVoltageMixed.cs example code. Also, it adds a new `SimplerMeasureAndPublishCurrentSmuOrPpmuOrDmm` example method to the MeasureVoltageMixed.cs that highlights the new filterPins parameter added to the TSMSessionManager members, which was introduced in the 24.5.1 release. Note that this is intentionally added as a separate example to leave the existing `SimpleMeasureAndPublishCurrentSmuOrPpmuOrDmm` example as is for 24.5.0 users (although it was intentionally renamed to add OrDmm at the end of the method name since it includes a DMM measure in the implementation).
The current example code in the ConcurrentCodeExecution.md user guide topic and the similar …
> Fix Example Code Implementation in ConcurrentCodeExecution.md and MeasureVoltageMixed.cs

- Examples/source/DataAbstraction/PinSiteDataExamples.cs
- Examples/source/DataAbstraction/SiteDataExamples.cs
Fixes the examples for constructing PinSiteData and SiteData with site-agnostic data (i.e. System pins). 
The current implementations are incorrect and are misleading to users.
Manually created ad-hoc unit tests (not committed) to run the code as-is to confirm no errors, and the constructed data was structured as expected.
> Fix Examples for Constructing PinSiteData/SiteData with Site-agnostic Data

- Examples/source/PatternTriggeredInstrumentControl/PatternTriggeredDmmMeasurement.cs
Removes the dependency on the `NationalInstruments.Restricted` namespace by updating the `GetDeviceInfo` private method implementation in the `PatternTriggeredDmmMeasurement` example to use the native `System.Array.IndexOf` method.
Ensure that public code is not using the `NationalInstruments.Restricted` namespace.
Verified that all code builds without error. No additional testing was done as the `System.Array.IndexOf` method is functionally equivalent to the `NationalInstruments.Restricted.EnumerableExtensions.IndexOf`.
> Remove Dependency on Restricted Namespace from Examples

- SemiconductorTestLibrary.Extensions/tests/Unit/InstrumentAbstraction/Digital/LevelsAndTimingTests.cs
- Added unit tests to for the `GetTimeSetEdge`, `GetTimeSetEdgeMultiplier` and `GetTimeSetDriveFormat` to address
This PR contains unit tests to increase the code coverage for the extension methods to get the timeset info.
- Unit tests are passed
> Add unit tests for better code coverage of Get TimeSet info extension methods

- SemiconductorTestLibrary.Extensions/source/InstrumentAbstraction/DCPower/Measure.cs
Updates the `DCPower.Measure.FetchMeasurement` Extension method to correctly return both voltage and current results. 
The current `DCPower.Measure.FetchMeasurement` implementation returns the voltage measurement twice instead of including the current measurement. This causes users to see identical values for both voltage and current measurement.
Auto tests are passing.
> Update FetchMeasurement DCPower Extension Method to Correctly Return Both Voltage and Current Results

- .github/workflows/pr-intake.yml
Recently NIBuild farm VMs have been pretty busy because of which pipeline runs need to wait for an agent to be available. So pr-intake timeout needs to be increased.
Increases pr-intake timeout to 3 hours instead of 1 hour.
NA
> Increase timeout for pr-intake to account peak dev times

- SemiconductorTestLibrary.Extensions/source/InstrumentAbstraction/Digital/HistoryRAM.cs
- Added default constructors for `HistoryRAMSettings` and `HistoryRAMTriggerSettings` classes.
This PR contains the implementation of missing class constructors as the documentation of the classes are not shown without a constructor in it.
- ![image](https://github.com/user-attachments/assets/a750867f-d81a-4faa-b785-8f8710bb71c0)
- ![image](https://github.com/user-attachments/assets/4ce98bf2-ab42-4c53-998a-65745afe29f0)
> [WriterReviewNeeded]Add missing constructors

- .github/workflows/gh-pages-deploy.yml
This PR forces the gh-pages-deploy workflow to use docfx v2.77 instead of the current latest v2.78.
As mentioned in the below PR, we observed some breaking changes if using docfx v2.78. So docfx version needs to be forced to older version 2.77 in the gh-pages-deploy workflow.
https://github.com/ni/semi-test-library-dotnet/pull/232
NA
> Updated gh-pages-deploy workflow to use docfx-2.77

- .github/workflows/auto-comment-fixed-issues.yml
- Adds a conditional check to the job execution.
`if: startsWith(github.ref, 'refs/heads/releases/')` 
- Ensures the comment-on-issues job only runs when a branch is created under the releases/ namespace.
- Prevents unnecessary execution of the job for non-release branches.
- Increases the reliability and precision of the workflow.
- Ensures that jobs only run in valid release branch contexts, maintaining clarity and control over automation behavior.
- Verified that the workflow still runs correctly on branches matching releases/*.
- Confirmed that the job is skipped for non-release branches using the new if condition.
- Ensured no changes to the logic for searching issues or posting comments, preserving existing functionality.
> Update auto-comment-fixed-issues.yml Workflow: Add Conditional Branch Filter

- .github/workflows/pr-build.yml
- .github/workflows/pr-test.yml
This PR adds an extra level of validation before calling the AzDo pipelines from GitHub workflows.
Recently I observed an issue where if a pr-intake workflow is not approved for 30 days, GitHub automatically cancels that workflow but even then the pr-build and pr-test get triggered sometimes.
To ensure the AzDo pipeline only triggers when the pr-intake workflow is approved, I added a level of validation in the pr-build and pr-test workflow. Now these workflows will check if the workflow triggering them, i.e., pr-intake should not be canceled or failed, if not then only it will call the AzDo pipeline or else exit safely.
I tested the workflow run in my forked repo. Final testing in this repo will be done once this PR merges in the main.
> PR workflow improvement

- SemiconductorTestLibrary.TestStandSteps/source/LeakageTest.cs
There is a mistake in `LeakageTest` that when serial operation is enabled, we currently is calling `MeasureAndPublishVoltage` while it should be `MeasureAndPublishCurrent`. This pull request corrects the mistake.
To fix an existing mistake.
N/A. Will enhance existing test suite so that it's able to catch this kind of mistakes before code submission.
> Fix LeakageTest

- TestAssets/Tests.SemiconductorTestLibrary.Utilities/TestFilters.cs
As the functionality test are added in `NationalInstruments.Tests.SemiconductorTestLibrary.dll`, so ats performance pipeline run them with performance test, which is not a correct workflow. So added a separate Enum for the filtration of performance test from other functionality test and only run performance test.
This PR contains the implementation for Enum `TestType`, which contains the value as `Performance` which will be used as trait to differentiate performance test from other functionality test present in same `NationalInstruments.Tests.SemiconductorTestLibrary.dll`.
Ran the [performance](https://dev.azure.com/ni/DevCentral/_build/results?buildId=14760184&view=logs&j=9316236d-33d1-5e32-58fc-bdb37708dc8b&t=5fdc2f3e-f982-5b43-c0e4-a5f2ba88c12d&l=59) pipeline form current branch.
> Adding the Enum for performance test

- SemiconductorTestLibrary.Extensions/tests/Unit/InstrumentAbstraction/Digital/LevelsAndTimingTests.cs
- We have a "[Bug 3191075](https://dev.azure.com/ni/DevCentral/_workitems/edit/3191075): Multiple digital test Failures in ATS Functionality pipeline". As a temporary solution to this Bug, we decided to skip the failing tests until the Digital Instrument card is calibrated in `LungYuan`.
- This PR makes changes to `SemiconductorTestLibrary.Extensions/tests/Unit/InstrumentAbstraction/Digital/LevelsAndTimingTests.cs` to skip the failing tests.
- We need to temporarily skip the failing tests; thus, we use the `Skip` attribute in all four failing tests.
- The `skip` attribute is used for the following methods:
- `TwoDevicesWorkForTwoSitesSeparately_MeasureTDROffsets_Succeeds`
- `OneDeviceWorksForOnePinOnTwoSites_MeasureTDROffsets_Succeeds`
- …
> Skip 'failing Tests' until Digital Instrument Card is calibrated in LungYuan

- .github/workflows/pr-intake.yml
- Adds conditional separation of `pr-intake` workflow based on the source of the pull request.
- Introduces two distinct jobs:
- `internal-wait-for-pr-build-and-test-workflows`: runs automatically for internal pull requests (from the same repository).
- `external-wait-for-pr-build-and-test-workflows`: runs for pull requests from forks, with `environment: gh-action-testing` to enforce manual approval.
- Maintains all original steps in both jobs without changes.
- Ensures manual approval is only enforced for forked PRs, improving security without blocking internal contributors.
- Avoids manual approval steps for internal changes.
- Uses a simple and maintainable structure while preserving the existing workflow steps.
- N/A
> Enhance pr-intake workflow to require environment approval for PRs from forked repositories only

- CHANGELOG.md
- This PR removes the line breaks in [CHANGELOG](https://github.com/ni/semi-test-library-dotnet/blob/main/CHANGELOG.md) file.
- The line breaks do not cause any issues in the `.md` files, but the CHANGELOG is copied to the Release Notes, which has line breaks that are not required.
- This is to maintain consistency between the CHANGELOG and the Release Notes.
- Removes all the line breaks that were not required.
- Checked the preview for the file.
> Remove Line Breaks in CHANGELOG.md
